name: .NET

on:
  push:
    branches:
    - main
    - divim-patch-1
  pull_request:
    branches: 
      - main
      - divim-patch-1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --configuration Release –-project AzureAppDevWorkshops/Azure App Service/Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj
    - name: Publish
      run: dotnet publish --configuration Release -o AzureAppDevWorkshops/Azure App Service/Tailspin.SpaceGame.Web/publish

